services:
  - type: web
    name: smart-parking-cv
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 10000
